name: tfsec
permissions: write-all
on:
  pull_request:
  workflow_dispatch:
jobs:
  basic:
    uses: clouddrove/github-shared-workflows/.github/workflows/tfsec.yml@1.2.4
    secrets: inherit
    with:
      working_directory: './examples/basic/'

  complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tfsec.yml@1.2.4
    secrets: inherit
    with:
      working_directory: './examples/complete/'    